[workspace]
authors = ["Anne Hartebrodt <anne.hartebrodt[a]fau.de>"]
channels = ["conda-forge", "bioconda"]
name = "grnfinder"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install-kernel = "python -m ipykernel install --user --name pixi_signifikante --display-name pixi_signifikante"


[dependencies]
anndata="*"
dask="*"
dask-core="*"
dask-expr="*"
distributed="*"
networkx="*"
numba = ">=0.61.2,<0.62"
numpy="*"
pandas="*"
scanpy="*"
scikit-learn="*"
scipy="*"
seaborn="*"
tqdm="*"
umap-learn="*"
ipykernel = ">=6.29.5,<7"
jupyterlab = ">=4.4.5,<5"
six = ">=1.17.0,<2"
scikit-learn-extra = ">=0.3.0,<0.4"
ipywidgets = ">=8.1.7,<9"
decoupler-py = ">=2.1.1,<3"
pingouin = ">=0.5.5,<0.6"

[pypi-dependencies]
seacells = { git = "https://github.com/dpeerlab/SEACells.git" }
signifikante = { git = "https://github.com/bionetslab/SignifiKANTE.git" }

